[package]
name = "rust_tests"
version = "0.1.0"
authors = ["Concordium AG <contact@concordium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
ed25519-dalek = "1.0.0"
sha2 = "0.9.2"
ledger = "0.2.5"