#ifndef _CONCORDIUM_APP_ERROR_CODES_H_
#define _CONCORDIUM_APP_ERROR_CODES_H_

enum {
    // Successfull codes
    SUCCESS = 0x9000,

    // Error codes
    ERROR_REJECTED_BY_USER = 0x6985,
    ERROR_INVALID_CLA = 0x6E00,
    
    ERROR_INVALID_STATE = 0x6B01,
    ERROR_INVALID_PATH = 0x6B02,
    ERROR_INVALID_PARAM = 0x6B03,
    ERROR_INVALID_TRANSACTION = 0x6B04,
    ERROR_INVALID_INSTRUCTION = 0x6D00
};

#endif

