name: Build and test

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

    # Allows us to run the workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    compile-nano-s:
        name: Compile for Nano S
        runs-on: ubuntu-latest

        container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'
            - name: Build
              run: |
                  make clean
                  BOLOS_SDK=$NANOS_SDK make
                  mv bin/app.elf concordium_nanos.elf

            - name: Upload binary
              uses: actions/upload-artifact@v3
              with:
                name: nanos
                path: ./concordium_nanos.elf

    compile-nano-s-plus:
        name: Compile for Nano S Plus
        runs-on: ubuntu-latest

        container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'

            - name: Build
              run: |
                  make clean
                  BOLOS_SDK=$NANOSP_SDK make
                  mv bin/app.elf concordium_nanosplus.elf

            - name: Upload binary
              uses: actions/upload-artifact@v3
              with:
                name: nanosplus
                path: ./concordium_nanosplus.elf

    compile-nano-x:
        name: Compile for Nano X
        runs-on: ubuntu-latest

        container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'

            - name: Build
              run: |
                  make clean
                  BOLOS_SDK=$NANOX_SDK make
                  mv bin/app.elf concordium_nanox.elf

            - name: Upload binary
              uses: actions/upload-artifact@v3
              with:
                name: nanox
                path: ./concordium_nanox.elf

    scan-build:
        name: Run Clang Static Analyzer
        runs-on: ubuntu-latest

        container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'

            - name: Clang Static Analyzer
              run: |
                  make clean
                  scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make default

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Lint
              uses: DoozyX/clang-format-lint-action@v0.15
              with:
                source: './src ./unit_tests'
                extensions: 'c,h'
                clangFormatVersion: 15
                style: file
                inplace: false

    e2e-tests:
        name: End to end tests
        needs: [compile-nano-s, compile-nano-s-plus, compile-nano-x]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                submodules: 'recursive'
            - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev

            - uses: actions/setup-node@v3
              with:
                node-version: "16"

            - name: Setup dependencies
              run: |
                cd tests && yarn

            - name: Create directory for binaries
              run: |
                mkdir tests/bin

            - name: Download binaries
              uses: actions/download-artifact@v3
              with:
                path: tests/bin

            - name: Run tests
              run: |
                cd tests && yarn test

            - name: Upload snapshots
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: snapshots
                path: ./tests/snapshots-tmp

    run_unit_test:
      name: Unit test
      runs-on: ubuntu-latest

      container:
        image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

      steps:
          - name: Clone
            uses: actions/checkout@v3

          - name: Build unit tests
            run: |
              cd unit_tests/
              cmake -Bbuild -H. && make -C build

          - name: Run unit tests
            env:
              CTEST_OUTPUT_ON_FAILURE: 1
            run: |
              cd unit_tests/
              make -C build test
