name: Build

on:
    push:
        branches: [master, setup-build-pipeline]
    pull_request:
        branches: [master]

    # Allows us to run the workflow manually from the Actions tab
    workflow_dispatch:

jobs: 
    compile-nano-s:
        runs-on: ubuntu-latest

        container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
            - name: Checkout
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Build
              run: |
                  make clean
                  make

    compile-nano-x:
        runs-on: ubuntu-latest

        container: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

        steps:
            - name: Checkout
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Build
              run: |
                  make clean
                  make BOLOS_SDK=nanox-secure-sdk